import { describe, expect, it } from "vitest";
import { existsSync } from "node:fs";
import path from "node:path";
import { stripMarkdown } from "../../src/lib/markdown";
import {
  ROOT,
  buildRouteSet,
  collectImageRefs,
  collectInternalLinks,
  contentFiles,
  imageFiles,
  isInternal,
  normalize,
} from "../helpers/content";

const CATEGORY_PAGES = ["bok", "annen-bok", "digitalt", "kalender", "smykke"];
const REQUIRED = {
  events: ["title", "date"],
  products: ["name", "category", "price"],
  reports: ["title", "year"],
  gallery: ["src", "alt"],
  pages: ["title"],
};

describe("image references", () => {
  const refs = collectImageRefs();
  const files = imageFiles();

  it("every referenced image file exists", () => {
    const missing = refs.filter((r) => !files.has(r.ref.split("/").pop()!));
    expect(missing).toEqual([]);
  });

  it("every jpg/png reference has a .webp sibling", () => {
    const missing = refs
      .filter((r) => /\.(jpe?g|png)$/i.test(r.ref))
      .filter((r) => !files.has(r.ref.split("/").pop()!.replace(/\.(jpe?g|png)$/i, ".webp")));
    expect(missing).toEqual([]);
  });

  it("every referenced image has responsive variants (480/960/1440w)", () => {
    const missing: string[] = [];
    for (const r of refs) {
      if (!/\.(jpe?g|png)$/i.test(r.ref)) continue;
      const base = r.ref.split("/").pop()!.replace(/\.(jpe?g|png)$/i, "");
      for (const w of [480, 960, 1440]) {
        if (!files.has(`${base}-${w}w.webp`)) missing.push(`${r.ref} @${w}w`);
      }
    }
    expect(missing).toEqual([]);
  });
});

describe("internal links", () => {
  const routes = buildRouteSet();
  const links = collectInternalLinks();

  it("every internal href resolves to a generated route or public asset", () => {
    const isPublicAsset = (href: string) => existsSync(path.join(ROOT, "public", href));
    // /pagefind/* is generated by the build (pagefind CLI) — covered by build tests + e2e crawl.
    const isGenerated = (href: string) => href.startsWith("/pagefind/");
    const broken = links.filter((l) => {
      if (!isInternal(l.href)) return false;
      if (isPublicAsset(l.href) || isGenerated(l.href)) return false;
      const h = normalize(l.href);
      return !routes.has(h) && !routes.has(h + "/");
    });
    expect(broken).toEqual([]);
  });

  it("route model covers all content entries", () => {
    for (const p of contentFiles("pages")) {
      const section = p.data.section || "historie";
      expect(routes.has(`/${section}/${p.slug}`)).toBe(true);
    }
    for (const r of contentFiles("reports")) {
      expect(routes.has(`/arsmeldinger/${r.slug}`)).toBe(true);
    }
  });
});

describe("frontmatter schemas", () => {
  for (const [collection, required] of Object.entries(REQUIRED)) {
    it(`${collection}: required fields present`, () => {
      const problems: string[] = [];
      for (const f of contentFiles(collection)) {
        for (const field of required) {
          if (f.data[field] === undefined) problems.push(`${f.slug}: missing '${field}'`);
        }
      }
      expect(problems).toEqual([]);
    });
  }

  it("products: price is a non-negative number", () => {
    const problems = contentFiles("products")
      .filter((p) => p.data.price === undefined || isNaN(Number(p.data.price)) || Number(p.data.price) < 0)
      .map((p) => p.slug);
    expect(problems).toEqual([]);
  });

  it("products: category maps to a category page", () => {
    const bad = contentFiles("products")
      .filter((p) => !CATEGORY_PAGES.includes(p.data.category))
      .map((p) => `${p.slug} (${p.data.category})`);
    expect(bad).toEqual([]);
  });

  it("reports: year is a number", () => {
    const bad = contentFiles("reports")
      .filter((r) => isNaN(Number(r.data.year)))
      .map((r) => r.slug);
    expect(bad).toEqual([]);
  });

  it("events: date is YYYY-MM-DD", () => {
    const bad = contentFiles("events")
      .filter((e) => !/^\d{4}-\d{2}-\d{2}$/.test(e.data.date || ""))
      .map((e) => `${e.slug} (${e.data.date})`);
    expect(bad).toEqual([]);
  });

  it("gallery: every entry has alt text", () => {
    const bad = contentFiles("gallery")
      .filter((g) => !g.data.alt || g.data.alt.length < 3)
      .map((g) => g.slug);
    expect(bad).toEqual([]);
  });

  it("pages: section is historie or om-oss", () => {
    const bad = contentFiles("pages")
      .filter((p) => !["historie", "om-oss"].includes(p.data.section || "historie"))
      .map((p) => p.slug);
    expect(bad).toEqual([]);
  });
});

describe("published gating", () => {
  it("no collection entry is unpublished (leakage guard)", () => {
    const unpublished: string[] = [];
    for (const collection of ["events", "products", "reports", "pages"]) {
      for (const f of contentFiles(collection)) {
        if (f.data.published === "false") unpublished.push(`${collection}/${f.slug}`);
      }
    }
    expect(unpublished).toEqual([]);
  });
});

describe("content sanity", () => {
  it("products without a price keep the 'Pris på forespørsel' rendering path valid", () => {
    const zeroPrice = contentFiles("products").filter((p) => Number(p.data.price) === 0);
    for (const p of zeroPrice) {
      expect(p.data.published !== "false").toBe(true);
    }
  });

  it("event bodies do not leak raw markdown markers that would render literally", () => {
    // stripMarkdown() must have removed ** markers; cards render plain text.
    const leaks = contentFiles("events")
      .filter((e) => stripMarkdown(e.body).includes("**"))
      .map((e) => e.slug);
    expect(leaks).toEqual([]);
  });
});
