version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "toreau/gh-workflows/.github/workflows/container-build-attest.yml"
    groups:
      github-actions:
        patterns:
          - "*"
